# Generated by Django 3.2.4 on 2021-06-08 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hippo_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('hostname', models.CharField(max_length=200)),
                ('dbname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hippo_app.sourcedb')),
            ],
        ),
    ]
